Init commit

diff --git a/.github/workflows/cloudflare-env.yaml b/.github/workflows/cloudflare-env.yaml
--- a/.github/workflows/cloudflare-env.yaml
+++ b/.github/workflows/cloudflare-env.yaml
@@ -53,6 +53,7 @@ jobs:
   convert:
     name: Update Cloudflare Worker Subscription
     runs-on: ubuntu-latest
+    timeout-minutes: 60
 
     steps:
     - name: Checkout repo
@@ -90,43 +91,42 @@ jobs:
     - name: Start Go program to generate all.yaml
       id: run_go_program
       run: |
-        go run . -f ./config/config.example.yaml &
-        echo $! > go.pid
+        go run . -f ./config/config.example.yaml
 
-    - name: Wait for proxies to be ready
-      run: |
-        URL="http://127.0.0.1:8199/all.yaml"
-        MAX_WAIT=3600   # 最多等 3600 秒
-        INTERVAL=30    # 每隔 30 秒检查一次
-        COUNT=0
+    # - name: Wait for proxies to be ready
+    #   run: |
+    #     URL="http://127.0.0.1:8199/all.yaml"
+    #     MAX_WAIT=3600   # 最多等 3600 秒
+    #     INTERVAL=30    # 每隔 30 秒检查一次
+    #     COUNT=0
 
-        echo "Waiting for $URL to have content..."
-        while true; do
-          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$URL" || echo "000")
-          if [ "$STATUS" = "200" ]; then
-            # 获取文件内容长度
-            SIZE=$(curl -s -L "$URL" | wc -c)
-            if [ "$SIZE" -gt 0 ]; then
-              echo "all.yaml is ready ($SIZE bytes)"
-              curl -s -L "$URL" > all.yaml
-              echo "Downloaded all.yaml"
-              cat all.yaml
-              break
-            fi
-          else
-            echo "Waiting for $URL to return 200 OK, current status: $STATUS"
-          fi
+    #     echo "Waiting for $URL to have content..."
+    #     while true; do
+    #       STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$URL" || echo "000")
+    #       if [ "$STATUS" = "200" ]; then
+    #         # 获取文件内容长度
+    #         SIZE=$(curl -s -L "$URL" | wc -c)
+    #         if [ "$SIZE" -gt 0 ]; then
+    #           echo "all.yaml is ready ($SIZE bytes)"
+    #           curl -s -L "$URL" > all.yaml
+    #           echo "Downloaded all.yaml"
+    #           cat all.yaml
+    #           break
+    #         fi
+    #       else
+    #         echo "Waiting for $URL to return 200 OK, current status: $STATUS"
+    #       fi
 
-          COUNT=$((COUNT + INTERVAL))
-          if [ "$COUNT" -ge "$MAX_WAIT" ]; then
-            echo "Timeout waiting for all.yaml"
-            exit 1
-          fi
+    #       COUNT=$((COUNT + INTERVAL))
+    #       if [ "$COUNT" -ge "$MAX_WAIT" ]; then
+    #         echo "Timeout waiting for all.yaml"
+    #         exit 1
+    #       fi
 
-          sleep $INTERVAL
-        done
+    #       sleep $INTERVAL
+    #     done
 
-    - name: Cleanup background processes
-      run: |
-        # 杀掉后台进程
-        [ -f go.pid ] && kill $(cat go.pid)
+    # - name: Cleanup background processes
+    #   run: |
+    #     # 杀掉后台进程
+    #     [ -f go.pid ] && kill $(cat go.pid)
